config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :flights
  resources :bookings, only: [:new, :create, :show]
  # Defines the root path route ("/")
  # root "articles#index"
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: :departure_airport_id
    has_many :arriving_flights, class_name: "Flight", foreign_key: :arrival_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_and_belongs_to_many :passengers, inverse_of: :passenger
    belongs_to :flight

    accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: "Airport"
    belongs_to :arrival_airport, class_name: "Airport"
    has_many :bookings

    def self.found_flights(params)
        Flight.where("DATE(start) = ? AND departure_airport_id = ? AND arrival_airport_id = ?",
            Date.parse(params["flight_date"]), params["departure_airport_id"], params["arrival_airport_id"])
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_and_belongs_to_many :bookings, inverse_of: :booking

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @params = params
        @flight = Flight.find(params["flight_id"])
        @num_tickets = params["num_tickets"]
        @booking = Booking.new
        @num_tickets.to_i.times { @booking.passengers.build }
    end
    
    def create
        @flight = Flight.find(params["flight_id"])
        @num_tickets = params["num_tickets"]
        @booking = Booking.new(booking_params())
        @booking.flight = @flight
        @flight.bookings << @booking
        passenger_ids = @booking.passengers.map {|p| p.id }

        if @booking.save
            PassengerMailer.with(passenger_ids: passenger_ids, flight: @flight).confirmation_email.deliver_later
            redirect_to booking_path(@booking, flight_id: @flight.id)
        else
            render :new, :unprocessable_entity
        end
    end

    def show
        @booking = Booking.find(params["id"])
        @flight = Flight.find(params["flight_id"])
        
    end

    private


    def booking_params
        params.require(:booking).permit(passengers_attributes: [:name, :email])
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

    def index
        @airport_options = Airport.all.map {|airport| [airport.airport_code, airport.id] }
        @num_ticket_options = (1..4).each {|ticket_amount| [ticket_amount, ticket_amount] }
        @flight_date_options = Flight.order(:start).distinct.map {|flight| [flight.start.strftime("%d/%m/%Y"), flight.start.strftime("%Y%m%d")] }.uniq
        @found_flights =  params.key?("flight_date") ? Flight.found_flights(params) : []
        @num_tickets = params[:num_tickets]
        @params = params
    end

    def new
        @params = params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div><%= link_to "Back To Flights", root_path %></div>
<h1>Booking</h1>

<strong>Chosen date: </strong>
<%= @flight.start %><br>

<strong>Departure Aiport: </strong>
<%= Airport.find(@flight.departure_airport_id).airport_code %><br>

<strong>Arrival Aiport: </strong>
<%= Airport.find(@flight.arrival_airport_id).airport_code %><br>

<strong>Flight Id: </strong>
<%= @flight.id %><br>

<%= form_with model: @booking do |form| %>
    Passengers:
    <%= form.fields_for :passengers do |passengers_form| %>
        <div>
            <%= passengers_form.label :name %>
            <%= passengers_form.text_field :name %>

            <%= passengers_form.label :email %>
            <%= passengers_form.email_field :email %>
        </div>
    <% end %>

    <%= hidden_field_tag :flight_id, @flight.id %>
    <%= hidden_field_tag :num_tickets, @num_tickets %>
    <div><%= form.submit "Book Flight" %></div>
<% end %>
        

app/views/bookings/show.html.erb
<div><%= link_to "Back To Flights", root_path %></div>
<h1>Your Booking</h1>

<h2>Flight</h2>

<strong>Chosen date: </strong>
<%= @flight.start %><br>

<strong>Departure Aiport: </strong>
<%= Airport.find(@flight.departure_airport_id).airport_code %><br>

<strong>Arrival Aiport: </strong>
<%= Airport.find(@flight.arrival_airport_id).airport_code %><br>

<strong>Flight Id: </strong>
<%= @flight.id %><br>


<h2>Passengers</h2>

<% @booking.passengers.each_with_index do |passenger, passenger_num| %>
    <h4>Passenger <%= passenger_num+1 %></h4>
    <div>
        <%= passenger.name %><br>
        <%= passenger.email %>
    </div>
<% end %>

app/views/flights/index.html.erb
<h1>Search Flights</h1>

<%= form_for :flight, method: :get do |form| %>
    <div>
    <%= form.label :departure_airport_id, "Departure airport: " %>
    <%= select_tag(:departure_airport_id, options_for_select(@airport_options)) %>
    </div>
    <br>

    <div>
    <%= form.label :arrival_airport_id, "Arrival airport: " %>
    <%= select_tag(:arrival_airport_id, options_for_select(@airport_options)) %>
    </div>
    <br>

    <div>
    <%= form.label :num_tickets, "Amount of tickets: " %>
    <%= select_tag(:num_tickets, options_for_select(@num_ticket_options)) %>
    </div>
    <br>
    
    <div>
    <%= form.label :flight_date, "Flight date: " %>
    <%= select_tag(:flight_date, options_for_select(@flight_date_options)) %>
    </div>
    <br>

    <div>
        <%= form.submit "Search flights" %>
    </div>
<% end %>

<h1>Found Flights</h1>
<%= form_with url: new_booking_path, method: :get do |form| %>
    <% check = true %>
    <% @found_flights.each do |flight| %>
        <div>
            <%= Airport.find(flight.departure_airport_id).airport_code %><br>
            <%= Airport.find(flight.arrival_airport_id).airport_code %><br>
            <%= flight.start %><br>
            <%= flight.duration %><br>
            <%= form.radio_button "flight_id", flight.id, checked: check %>
            <% check = false %>
        </div><br>
    <% end %>

    <%= form.hidden_field :num_tickets, value: @num_tickets %>
    <%= form.submit "Select flight" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>